# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dMdiuGycCxlo64Uyx3CHjtUyrGC0xN5Y
"""

from sklearn.calibration import calibration_curve
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import itertools

import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from torch.optim import lr_scheduler

class CNNModel(nn.Module):
    def __init__(self):
        super(CNNModel, self).__init__()

        self.c1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=(5,5), stride=1, padding=0)
        self.relu1 = nn.ReLU()

        self.maxpool1 = nn.MaxPool2d(kernel_size=(2,2))

        self.dropout1 = nn.Dropout(0.25)

        self.c2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=(3,3), stride=1, padding=0)
        self.relu2 = nn.ReLU()

        self.maxpool2 = nn.MaxPool2d(kernel_size=(2,2))

        self.dropout2 = nn.Dropout(0.25)

        self.fc1 = nn.Linear(32*5*5, 256)

        self.dropout3 = nn.Dropout(0.25)

        self.fc2 = nn.Linear(256, 10)